songs: [
    "swordland",
    "feel_uneasy",
    "everyday_life",
    "quiet_strain",
    "no_way",
    "stand_at_bay",
    "weird_place",
    "survive_the_swordland",
    "taut_nerves",
    "a_tense_situation",
    "a_strategy_meeting",
    "in_your_past",
    "march_down",
    "left_in_suspense",
    "we_have_to_defeat_it",
    "at_our_parting",
    "confront_battle",
    "at_our_parting_piano",
    "luminous_sword",
    "at_our_parting_vc",
    "a_close_battle",
    "a_tender_feeling",
    "a_narrow_escape",
    "he_rules_us",
    "fight",
    "a_tiny_love",
    "smile_for_me",
    "gracefully",
    "a_squabble",
    "with_my_friend",
    "the_first_town",
    "at_nightfall",
    "despaired"
]